server:
  port: 8095

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/bitmoi?autoReconnect=true
    username: bitmoi
    password: bitmoi6!
#    pool:
#      initial-size: 100
#      max-size: 500
#      max-idle-time: 30m
#      validation-query: SELECT 1
  logging:
    level:
      org.springframework.data.r2dbc: Debug


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bitmoi
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties.spring.json.trusted.packages: com.bitmoi
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.JsonSerializer
    properties.spring.json.add.type.headers: false

