server:
  port: 8095

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: order-serice
  r2dbc:
    url: r2dbc:mysql://localhost:13306/bitmoi?autoReconnect=true
    username: bitmoi
    password: bitmoi6!
#    pool:
#      initial-size: 100
#      max-size: 500
#      max-idle-time: 30m
#      validation-query: SELECT 1
  logging:
    level:
      org.springframework.data.r2dbc: Debug


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bitmoi
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.JsonSerializer

jwt:
  secret: Y29kZXN0YXRlcy1iaXRodW1iLW1zYS10ZWFtLW1lbWJlci1zcHJpbmctYm9vdC13ZWJmbHV4LWp3dC1zZWNyZXQ
