server:
  port: 8095

springdoc:
  api-docs:
    groups:
      enabled: true


#?characterEncoding=utf8&serverTimezone=Asia/Seoul
spring:
  #  liquibase:
  #    url: jdbc:mysql://localhost:13306/msa
  #    user: bitmoi
  r2dbc:
    url: r2dbc:mysql://localhost:3306/msa
    username: bitmoi
    password: bitmoi6!
    port: 3306
    initialization-mode: always
  logging:
    level:
      org.springframework.data.r2dbc: Debug
#    url: r2dbc:h2:mem:///msa;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
#    username: sa
#    password:
#    initialization-mode: always
#    port: 9093
#  h2:
#    console:
#      enabled: true

#  jpa:
#    defer-datasource-initialization: true




  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bitmoi
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.JsonSerializer
    value-serializer: org.apache.kafka.common.serialization.JsonSerializer


